### ISSUE TITLE
Some captions in scenes folder is missing during runing the generate_images.sh.

### ISSUE THREAD

**Issue by Ph0eNiX0803** [cvpaperchallenge/Describing-and-Localizing-Multiple-Change-with-Transformers#5]
![向日葵 2021_12_17 10_46_11](https://user-images.githubusercontent.com/32815527/146480882-6b3f58df-f9da-4b4f-afd7-a9e582c10486.png)
![向日葵 2021_12_17 10_51_21](https://user-images.githubusercontent.com/32815527/146481066-b5aa291b-3573-47b0-862e-f43c43d3fe16.png)
![向日葵 2021_12_17 10_51_48](https://user-images.githubusercontent.com/32815527/146481073-a8fa524a-3822-4103-b99d-591ade2a3175.png)
I ran the code from 0 to 3, it generated 4 sets images but got only 2 captions.

**Comment by qiuyue1993** [comment]
Thank you so much for reporting the generation result. During our generation, we also faced the same problem. We solved this by removing the data without captions during post-processing. If you have enough computing resources and memory for your computer, you can consider the same post-processing with us. It could also be an alternative to add a function to delete the failed examples during dataset generation.

**Comment by tuyunbin** [comment]
@Ph0eNiX0803 Hi, how many image pairs do you generate finally?
