### ISSUE TITLE
Request to share WORDMAP_3dcc_5_cap_per_img_0_min_word_freq.json

### ISSUE THREAD

**Issue by sumitramalagi** [cvpaperchallenge/Describing-and-Localizing-Multiple-Change-with-Transformers#6]
Hi, Dr. Qiu, Thank you for sharing the code repository. I was trying to train the model and met with the following error:
FileNotFoundError: [Errno 2] No such file or directory: 'WORDMAP_3dcc_5_cap_per_img_0_min_word_freq.json'
Could please share the steps to generate the json file. Also, the files 1."TRAIN_IMAGE_FEATURES_1_3dcc_5_cap_per_img_0_min_word_freq.h5"  
2. '_CAPLEN_' (is it caption length or number of captions), can you please share an example file.

**Comment by qiuyue1993** [comment]
Hi, Dr. sumitramalagi.
Thank you so much for trying out the code.

- 'WORDMAP_3dcc_5_cap_per_img_0_min_word_freq.json' is a file that maps words to ids. 
- "TRAIN_IMAGE_FEATURES_1_3dcc_5_cap_per_img_0_min_word_freq.h5" is a file that saves the image features (extracted using ResNet101) of training image pairs.
- As you mentioned, 'CALPEN' is the caption length.

I have uploaded the  'WORDMAP_3dcc_5_cap_per_img_0_min_word_freq.json'  and 'CAPLEN' files [here](https://github.com/cvpaperchallenge/Describing-and-Localizing-Multiple-Change-with-Transformers/tree/main/dataset_generation/test%20examples)

**Comment by sumitramalagi** [comment]
Thank you for sharing the files.
